# Generated by Django 5.1.1 on 2024-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('adult_count', models.PositiveIntegerField()),
                ('children_count', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('executive', 'Executive'), ('standard', 'Standard')], max_length=20)),
                ('rooms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
